version: "3.0"

services:
  server:
    container_name: server
    restart: always
    build: ./server
    env_file:
      - ./server/.env
    # volumes:
    #   - .:/app
    #   - .:/app/node_modules
    ports:
      - 8080:8080
    depends_on:
      - postgres

  client:
    container_name: client-container
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  postgres:
    container_name: postgres
    image: postgres:13.3
    env_file:
      - ./server/.env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: b08XI1S7
      POSTGRES_DB: wallets
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
